name: Run NREGA scraper (direct)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"   # रोज़ाना 07:30 IST (02:00 UTC)

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps

      - name: Quick NIC connectivity check
        run: |
          set -e
          for U in \
            "https://nreganarep.nic.in/netnrega/app_issue.aspx?page=b&state_code=17" \
            "https://nreganarep.nic.in/netnrega/dpc_sms_new.aspx?lflag=eng&page=b&state_code=17" \
            "https://nreganarep.nic.in/netnrega/dpc_sms_new_dtl.aspx?page=d&state_code=17"
          do
            echo "Probing: $U"
            curl -I --max-time 20 -A "Mozilla/5.0" "$U" || echo "curl failed for $U"
          done

      - name: Run all scripts
        env:
          GOOGLE_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}
        run: node runall.cjs