name: Run Root Scripts

# Manual trigger + scheduled daily run
on:
  workflow_dispatch:
  schedule:
    # Runs daily at 07:00 IST => 01:30 UTC
    - cron: "30 1 * * *"

jobs:
  run-root:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Write GOOGLE_CREDENTIALS to file (from secret)
        if: ${{ secrets.GOOGLE_CREDENTIALS_BASE64 != '' }}
        run: |
          echo "$GOOGLE_CREDENTIALS_BASE64" | base64 -d > creds.json
          ls -l creds.json
        shell: bash

      - name: List repo root (debug)
        run: |
          echo "Repo root contents:"
          ls -la
          echo "Node version:"
          node -v
          echo "NPM version:"
          npm -v

      - name: Run runall.cjs (root-level runner)
        run: node runall.cjs
        env:
          # make secret available to node processes if needed
          GOOGLE_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}
