name: Run NREGA scraper (no deploy)

on:
  workflow_dispatch:        # manually run from Actions tab
  schedule:
    - cron: "0 2 * * *"     # रोज़ 07:30 IST (02:00 UTC)

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Resume Render service (idempotent)
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          SERVICE_ID: srv-d2m0o3n5r7bs73e6oc20
        run: |
          curl -fsS -X POST "https://api.render.com/v1/services/$SERVICE_ID/resume" \
            -H "Authorization: Bearer $RENDER_API_KEY" || true
          # wait until health is up (max ~3 min)
          for i in {1..18}; do
            if curl -fsS "https://nrega-render.onrender.com/health" >/dev/null; then
              echo "Service healthy"; break
            fi
            echo "Waiting for health..."; sleep 10
          done

      - name: Trigger /run
        run: |
          curl -fsS "https://nrega-render.onrender.com/run" || exit 1
          # optional: wait until job finishes (poll health)
          for i in {1..60}; do
            out=$(curl -fsS "https://nrega-render.onrender.com/health" || true)
            echo "$out"
            echo "$out" | grep -q '"isRunning":false' && break
            sleep 10
          done

      - name: Suspend Render (fallback)
        if: always()
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          SERVICE_ID: srv-d2m0o3n5r7bs73e6oc20
        run: |
          curl -fsS -X POST "https://api.render.com/v1/services/$SERVICE_ID/suspend" \
            -H "Authorization: Bearer $RENDER_API_KEY" || true
