name: NREGA Scraper Daily

on:
  schedule:
    - cron: '0 7 * * *' # daily 7AM IST
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run Render Service Script
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          GOOGLE_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}
          PROXY_SERVER: ${{ secrets.PROXY_SERVER }}
          PROXY_USER: ${{ secrets.PROXY_USER }}
          PROXY_PASS: ${{ secrets.PROXY_PASS }}
        run: node render-service.js
