name: Trigger Render Redeploy

on:
  schedule:
    # रोज़ सुबह 7:00 AM IST → 01:30 UTC
    - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Call Render Deploy Hook
        run: |
          set -e
          curl -fsS -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
