name: Trigger Render Redeploy

on:
  schedule:
    - cron: "30 1 * * *"   # 07:00 IST
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Call Render Deploy Hook
        run: |
          set -e
          curl -fsS -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
